#cloud-config
# Add groups to the system
# Adds the ubuntu group with members 'root' and 'sys'
# and the empty group hashicorp.
groups:
  - ubuntu: [root,sys]
  - hashicorp

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: terraform
    gecos: terraform
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    ssh_import_id:
    lock_passwd: false
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDX1nHOT2YyqWA1bQ2qndCoNykneVnO70lEW40Wp6S/L/2hvS9CPY7S6lOOBakMOo3uXHf/xx4fvzfLxgwGdGCLJ1rPaROkj6qqI/FuqmzejS4utVRT4A4gNSVIEB2pNGg3GwVjxXaHbzQrCEmECake2fRvkpo1hyV0C3x7KXYW76tGh5kWuRWnLd4gH9yYiQmEYHlVpSYHJO0Fyu0CpACjlklzoTAqNv7+aSieHd/ZoL7oO+WunZByn4Ou/IkJB3ryoGS9f2UJ7Wtfpj5xXopFJLEv6znUewzaa6saMleGthW8upC22rtj/l/fQn+rBKeV0asUmzJbIbLuf51kCgrnDquzl7bWKfvLS4t1G48c7ChjHofO7Qztxie86bopGRQujFfNLG7psYPpoX0OJ3pu5D2JIkBt1hPP7R1JXmImWM/Tp01MSqmOFn5EMqN0qlhXCatlZ5tID57Q1nD+463GK74EmnXWkiPO4Xnlc1JhpE3UwaJ2L9UIzkufHVvpGlM= cloudinit@example.com

# Downloads the golang package
packages:
  - golang-go

# Setsthe GOPATH & downloads the demo payload
runcmd:
  - sudo su terraform
  - sudo mkdir ~/go
  - export GOPATH=$HOME/go
  - sudo go get github.com/hashicorp/learn-go-webapp-demo
